---
# githuname: checks

name: "Create Backport"
  #on:
  #  pull_request:
  #    types: [ closed ]
  #jobs:
  #  merge_job:
  #    if: github.event.pull_request.merged == true
on: [push]
env:
  #FIX: org change
  redmine_user_id: dupadhya
  redmine_key: "${{ secrets.REDMINE_KEY }}"
  github_user: ideepika
  github_token: "${{ secrets.GITHUB_TOKEN }}"
  fork_remote: https://github.com/ideepika/ceph.git
jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message
        run: |
          echo PR #${{ github.event.number }} has been merged
          echo ${{ toJSON(github.event.pull_request.commits) }}
          echo ${{ toJSON(github.event.commits[0].message) }}
          echo ${{ toJSON(github.event.head_commit.message) }}
          echo ${{ toJSON(github.event.pull_request.head.sha) }}
          echo ${{ toJSON(github.event.commits.*.message) }}
          echo ${{ github.event.pull_request.commits }}
          echo $(git log -1 --pretty=format:"%s")
      - name: Get Commit Message
        run: |
          MSG=$(git log --format=%B -n 1 ${{ github.event.after }})
          echo "::set-env name=COMMIT_MESSAGE::${MSG}"
          #      - name: set tracker to PR id
          #        if: "!contains(github.event.pull_request.commits, 'tracker.ceph')

