name: "Test Backport Script"
on:
  push:
  #  pull_request:
  #    types:
  #      - edited
  #      - opened
  #      - reopened
jobs:
  test_backport:
    runs-on: ubuntu-latest
    steps:
      - name: run backport testing script
        run: ls -al && MY_IP=$(ip r show default | cut -f3 -d' ') ./src/test/run-ceph-backport-tests.sh
