---
name: "Create Backport"
on:
  pull_request:
    types: [ closed ]
jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          # for pull_request so we can do HEAD^2
          fetch-depth: 2
      - name: Cache dependencies
      # cache dependencies
      #        uses: actions/cache@v2
      #  with:
      #   path: ~/.cache/pip
        run: |
          pip3 install python_redmine
      - name: Run backport-create-issue script
        env:
          #FIX: org change
          redmine_key: ${{ secrets.REDMINE_KEY }}
          github_token: ${{ secrets.TOKEN }}
          github_user: dexter816
          fork_remote: https://github.com/dexter816/ceph.git
        run: |
          echo PR #${{ github.event.number }} has been merged
          commit_msg=$(git log --format=%B -n 1 HEAD^2)
          tracker_id=$(echo "$commit_msg" | grep "tracker.ceph" | cut -d"/" -f5)
          echo $tracker_id
          if [[ -n $tracker_id ]]; then
            res=$(python ./src/script/backport-create-issue "$tracker_id:${{ github.event.number }}" --redmine-key env.redmine_key)
          fi
          backport_log=$(echo "$res" | grep -q "backport_tracker_ids:")
          if "$backport_log" ; then
            backport_tracker_ids=$(echo $backport_log | grep "backport_tracker_ids:" | awk '{split($0,a,":"); print a[2];}')
            for i in $(echo "$backport_tracker_ids" | sed "s/,/ /g")
            do
               echo "running backports cherrypicking for tracker $i"
               ./src/script/ceph-backport.sh "$i" --redmine-key env.redmine_key --github-user env.github_user --github-token env.github_token --debug
            done
          fi

