name: "Test Backport Script"
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
jobs:
  runs-on: python:3.8-buster
  run: |
    MY_IP=$(ip r show default | cut -f3 -d' ')  src/test/run-ceph-backport-tests.sh
