---
name: "Create Backport"
on:
  pull_request:
    types: [ closed ]
env:
  #FIX: org change
  redmine_user_id: dupadhya
  redmine_key: "${{ secrets.REDMINE_KEY }}"
  github_user: ideepika
  fork_remote: https://github.com/ideepika/ceph.git
jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          # for pull_request so we can do HEAD^2
          fetch-depth: 2
      - name: Check commit message
        run: |
          echo PR #${{ github.event.number }} has been merged
          echo ${{ toJSON(github.event.pull_request.head.sha) }}
          echo $(git log --format=%B -n 1 HEAD^2)

