---
name: "Create Backport"
on:
  pull_request:
    types: [ closed ]
env:
  #FIX: org change
  redmine_user_id: dupadhya
  redmine_key: "${{ secrets.REDMINE_KEY }}"
  github_user: ideepika
  fork_remote: https://github.com/ideepika/ceph.git
jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          # for pull_request so we can do HEAD^2
          fetch-depth: 2
      - name: Cache dependencies
      # cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/src/script/requirements.txt') }}
          restore-keys: |
           ${{ runner.os }}-pip-
      - name: Check commit message
        run: |
          echo PR #${{ github.event.number }} has been merged
          commit_msg=$(git log --format=%B -n 1 HEAD^2)
          tracker_id=$(echo $commit_msg | grep "tracker.ceph" | cut -d"/" -f5)
          python ./src/script/backport-create-issue "$tracker_id:${{ github.event.number }}"


