---
name: "Create Backport"
on:
  pull_request:
    types: [ closed ]
env:
  #FIX: org change
  redmine_user_id: dupadhya
  redmine_key: "${{ secrets.REDMINE_KEY }}"
  github_user: ideepika
  github_token: "${{ secrets.GITHUB_TOKEN }}"
  fork_remote: https://github.com/ideepika/ceph.git
jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: |
          echo PR #${{ github.event.number }} has been merged
          echo ${{ toJSON(github.event.pull_request.commits) }}
          echo ${{ toJSON(github.event.commits[0].message) }}
          echo ${{ toJSON(github.event.head_commit.message) }}
          echo ${{ toJSON(github.event.pull_request.head.sha) }}
          echo ${{ toJSON(github.event.commits.*.message) }}
          tracker_id=$(${{ toJSON(github.event.commits.*.message) }} | grep "tracker.ceph" | cut -d"/" -f5)
          echo $tracker_id
          #      - name: Update issues with PR ID
          #        run: ./src/script/backport-create-issue () --force --resolve-parent
          #
          #
          #
          #
          #      - name: Update Tracker
          #          #      - name: set tracker to PR id
          #          #        if: "!contains(github.event.pull_request.commits, 'tracker.ceph')
          #

        #TODO
